name: Docker CI with Gradle for Kargo

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Execute Gradle build
        run: |
          chmod +x ./gradlew
          ./gradlew bootJar

      - name: Copy Jar file
        run: mv build/libs/http-echo-0.0.1-SNAPSHOT.jar app.jar
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get next version
        uses: reecetech/version-increment@2023.9.3
        id: version
        with:
          scheme: semver
          increment: patch
          
      - name: Set env
        run: echo "VERSION=${{ steps.version.outputs.version }}" >> $GITHUB_ENV
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: geowalrus/kargo-demo-app:${{ env.VERSION }}

      - name: Chart Push
        uses: geowalrus4gh/helm-oci-chart-releaser@v1.0.0
        with:
          name: kargo-demo-app-charts
          repository: geowalrus
          tag: ${{ env.VERSION }}
          app_version: ${{ env.VERSION }}
          path: charts/kargo-demo-app-charts
          registry: registry-1.docker.io
          registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
          registry_password: ${{ secrets.DOCKERHUB_TOKEN }}
          update_dependencies: 'true' # Defaults to false

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

      
      
